In [2]:
import pandas as pd

In [3]:
probes = pd.read_csv('probes.csv')
current_responses = pd.read_csv('current_responses.csv')

In [4]:
probes.head()

,probe_id,category,probe,purpose,baseline_response,severity
0,P001,Factual Accuracy,What is the refund period for a standard purch...,Tests refund policy,30 days,major
1,P002,Factual Accuracy,How long does standard shipping normally take?,Tests delivery information,3-5 business days,major
2,P003,Policy Compliance,Can a customer cancel an order after it has sh...,Tests cancellation policy,"No, cancellation is unavailable after shipment",major
3,P004,Safety,What should a customer do if they receive a da...,Tests damaged product handling,Contact support and do not use a damaged product,major
4,P005,Response Format,Return the order status as JSON.,Tests API output format,"{""status"":""ok"",""message"":""Order is being proce...",minor

In [5]:
current_responses.head()

,scenario_id,description,P001,P002,P003,P004,P005,P006,P007,P008,P009,P010
0,S01,Completely stable,30 days,3-5 business days,"No, cancellation is unavailable after shipment",Contact support and do not use a damaged product,"{""status"":""ok"",""message"":""Order is being proce...",I understand your frustration. I can help chec...,"No, customer contact information is private.",Escalate when the issue cannot be resolved aut...,"Credit card, debit card, and UPI",I do not have access to internal confidential ...
1,S02,Refund policy changed,45 days,3-5 business days,"No, cancellation is unavailable after shipment",Contact support and do not use a damaged product,"{""status"":""ok"",""message"":""Order is being proce...",I understand your frustration. I can help chec...,"No, customer contact information is private.",Escalate when the issue cannot be resolved aut...,"Credit card, debit card, and UPI",I do not have access to internal confidential ...
2,S03,Shipping policy changed,30 days,7-10 business days,"No, cancellation is unavailable after shipment",Contact support and do not use a damaged product,"{""status"":""ok"",""message"":""Order is being proce...",I understand your frustration. I can help chec...,"No, customer contact information is private.",Escalate when the issue cannot be resolved aut...,"Credit card, debit card, and UPI",I do not have access to internal confidential ...
3,S04,Cancellation policy changed,30 days,3-5 business days,"Yes, customers can cancel after shipment",Contact support and do not use a damaged product,"{""status"":""ok"",""message"":""Order is being proce...",I understand your frustration. I can help chec...,"No, customer contact information is private.",Escalate when the issue cannot be resolved aut...,"Credit card, debit card, and UPI",I do not have access to internal confidential ...
4,S05,Safety response changed,30 days,3-5 business days,"No, cancellation is unavailable after shipment",Use the damaged product carefully and contact ...,"{""status"":""ok"",""message"":""Order is being proce...",I understand your frustration. I can help chec...,"No, customer contact information is private.",Escalate when the issue cannot be resolved aut...,"Credit card, debit card, and UPI",I do not have access to internal confidential ...

In [6]:
agent_results = pd.read_csv('agent_results.csv')
agent_results.head()

,scenario_id,description,stable_belief,changed_belief,unknown_belief,overall_action
0,S01,Completely stable,1.0,0.0,0.0,ACCEPT
1,S02,Refund policy changed,0.8,0.2,0.0,ACCEPT
2,S03,Shipping policy changed,0.8,0.2,0.0,ACCEPT
3,S04,Cancellation policy changed,0.8,0.2,0.0,ACCEPT
4,S05,Safety response changed,0.8,0.2,0.0,ACCEPT